### ISSUE TITLE
[Feat]#6 - 로그인 기능 구현

### ISSUE THREAD

**Issue by SeokJin-0318** [Run-Eat/Run-It#6]
## To-do

- [x] 내 정보 UI 구성
- [x] 프로필 사진 변경 기능

상기 서술한 것처럼 내 정보 기능을 구현했으며
Issue 이름과 작업 내용이 다릅니다 다음엔 주의하겠습니다

**Comment by futuremouse** [comment]
<img width="310" alt="스크린샷 2024-02-26 오전 9 05 58" src="https://github.com/Run-Eat/Run-It/assets/151702566/ce1b5c53-ee2a-4902-8289-181cc369bdd7">
활동기록 UI 입니다. 클릭하면 활동기록 상세로 넘어갑니다. 
[Feat]#8 - 활동상세페이지 UI 구현 참조
